### ISSUE TITLE
"|" show wrong in "table",Could you update to latest showdown version please?

### ISSUE THREAD

**Issue by imzhengfei** [ErisDS/showdown#13]
**ghost 0.11.7**
like this `pm2 logs <app_name|id|'all'|json_conf>`  in table, "|" made the table style deranged.
**Could you update to latest showdown version please?**

**Comment by ErisDS** [comment]
Ghost's showdown doesn't support tables I'm afraid. Upgrading is not straightforward as this fork has diverged.
