### ISSUE TITLE
"-" aways compiled to "·”. Could you update to latest showdown version please?

### ISSUE THREAD

**Issue by imzhengfei** [ErisDS/showdown#14]
**ghost 0.11.7**
A suggestion: please compiled "-" with spaces before and after "-", even at the start of a line, the "-" should be compiled with a space after. Even the ">", and other rules, if no space after them, don not compiled.
**AND**
**Could you update to latest showdown version please?**

**Comment by ErisDS** [comment]
I'm not sure what this means. Can you please provide full details? Should this maybe be raised as a bug against Ghost?

**Comment by imzhengfei** [comment]
OK, I'll raise this bug against Ghost.
